default: &default
  adapter: postgresql
  database_url: <%= ENV['DATABASE_URL'] %>
  encoding: unicode
  password: <%= ENV['DATABASE_PASSWORD'] %>
  username: <%= ENV['DATABASE_USER'] %>
development:
  <<: *default
  database: mattkelly_io_db_dev
  username: mathisto
  pool: 2
test:
  <<: *default
  database: mattkelly_io_db_test
  pool: 2
production:
  <<: *default
  database: mattkelly_io_db
  host: mattkelly.io
  pool: 5
