default: &default
  adapter: postgresql
  database_url: <%= ENV['DATABASE_URL'] %>
  encoding: unicode
  password: <%= ENV['DATABASE_PASSWORD'] %>
  username: <%= ENV['DATABASE_USER'] %>
  pool: 5
  host: 127.0.0.1
development:
  <<: *default
  database: mattkelly_io_db_dev
  username: mathisto
test:
  <<: *default
  database: mattkelly_io_db_test
production:
  <<: *default
  database: mattkelly_io_db
